# SPDX-FileCopyrightText: 2020 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

on:
  release:
    types: [published]
name: "Publish Helm Charts"
jobs:
  helm:
    name: Package and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install yq"
        run: |
          sudo snap install yq
      - name: "Publish Helm Charts"
        env:
          HELM_REGISTRY: https://charts.securecodebox.io
          USERNAME: ${{ secrets.HELM_REGISTRY_USERNAME }}
          PASSWORD: ${{ secrets.HELM_REGISTRY_PASSWORD }}
        run: |
          RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          # Remove leading 'v' from git tag to create valid semver
          RELEASE_VERSION="${RELEASE_VERSION//v}"
          # Publish all helm charts in all folders containing a `Chart.yaml` file
          # https://github.com/koalaman/shellcheck/wiki/SC2044
          find . -type f -name Chart.yaml -print0 | while IFS= read -r -d '' chart; do
          (
            dir="$(dirname "${chart}")"
            cd "${dir}" || exit
            echo "Processing Helm Chart in $dir"
            helm package --version $RELEASE_VERSION .
            NAME=$(yq eval '.name' - < Chart.yaml)
            curl --silent --show-error --user "${USERNAME}:${PASSWORD}" --data-binary "@${NAME}-${RELEASE_VERSION}.tgz" "${HELM_REGISTRY}/api/charts"
            sleep 5s
          )
          done
